name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt install libdbus-1-dev pkg-config
    - name: Build
      run: cargo build --verbose
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt install libdbus-1-dev pkg-config
    - name: Run tests
      run: cargo test --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt install libdbus-1-dev pkg-config
    - name: Run clippy
      run: cargo clippy --verbose
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt install libdbus-1-dev pkg-config
    - name: Check formatting
      run: cargo fmt --check --verbose
